###################################
#         Global settings         #
###################################
# Both or either one of http/https ports must be specified
listen_port_tls = 8443
https_redirection_port = 443

# Optional for h2 and http1.1
tcp_listen_backlog = 1024

# Optional for h2 and http1.1
max_concurrent_streams = 100

# Optional. Counted in total for http1.1, 2, 3
max_clients = 512

# Optional: Listen [::]
listen_ipv6 = true

###################################
#         Backend settings        #
###################################
[apps]

######################################################################
## Registering a backend app served by a domain name "localhost"
[apps.dist]
server_name = 'marekvrbka.cz' # Domain name

tls = { https_redirection = true, tls_cert_path = '/etc/certificates/server.pem', tls_cert_key_path = '/etc/certificates/server.key' }

[[apps.dist.reverse_proxy]]
upstream = [{ location = 'root-dist:4000', tls = false }]

[[apps.dist.reverse_proxy]]
path = '/assembly'
replace_path = '/'
upstream = [{ location = 'assembly-dist:4001', tls = false }]
