log_level = "debug"
log_target = "stdout"
worker_count = 1
max_connections = 500
max_buffers = 500
buffer_size = 16384
activate_listeners = true

[[listeners]]
protocol = "https"
address = "[::]:8443"

certificate = "/etc/certificates/server.pem"
key = "/etc/certificates/server.key"

[clusters]

[clusters.assembly-dist]
protocol = "http"

frontends = [
  { address = "[::]:8443", hostname = "marekvrbka.cz", path = "/assembly" }
]

backends = [
  { address = "127.0.0.1:4001", backend_id = "assembly-dist"}
]

[clusters.root-dist]
protocol = "http"

frontends = [
  { address = "[::]:8443", hostname = "marekvrbka.cz" }
]

backends = [
  { address = "127.0.0.1:4000", backend_id = "root-dist"}
]

